### ISSUE TITLE
No such file or directory: 'test/N4/ORCA4/UHF/SVP/N4.molden.input'

### ISSUE THREAD

**Issue by TApplencourt** [Konjkov/molden2qmc#12]
Hi,

When running the unit tests,
two fails due to  `test/N4/ORCA4/UHF/SVP/N4.molden.input` missing.

```
./test_molden2qmc.py
..........s.s.s.sE................E...s.s.....
======================================================================
ERROR: test_UHF_SVP (__main__.test_NwChem)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./test_molden2qmc.py", line 354, in test_UHF_SVP
    with open('test/N4/ORCA4/UHF/SVP/N4.molden.input', "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'test/N4/ORCA4/UHF/SVP/N4.molden.input'

======================================================================
ERROR: test_UHF_SVP (__main__.test_PSI4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./test_molden2qmc.py", line 116, in test_UHF_SVP
    with open('test/N4/ORCA4/UHF/SVP/N4.molden.input', "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'test/N4/ORCA4/UHF/SVP/N4.molden.input'

----------------------------------------------------------------------
Ran 46 tests in 5.409s

FAILED (errors=2, skipped=6)
```

PS: `test/N4/ORCA/UHF/SVP/N4.molden.input` exists (without *4*), but if we use those files,  the tests are not passings.

**Comment by Konjkov** [comment]
Thanks for the comment, these files have not been committed since December 2019, because the test fails due to poor convergence of the UHF/def2-SVP calculation.
CFOUR = -216.814103763816377
DALTON = UHF not available
MOLPRO = -216.813888503788
NWCHEM = -216.817928211776
ORCA 3.X = -216.814439323572 [59de655b7cca5651362218d6bf27d45fd9baddc8](https://github.com/Konjkov/molden2qmc/commit/59de655b7cca5651362218d6bf27d45fd9baddc8#diff-8c3898d6a6aaea247211e576fcd2a1d6)
ORCA 4.X = -216.814445563974
PSI4 0.4 = -216.8035322568761103
QCHEM = no data
TURBOMOL = -216.81410351408
I have committed these files but the test will fail.
Need to change the test system for the UHF calculation, any suggestions.
